# Generated by Django 5.1.2 on 2024-10-26 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('tipo_atividade', models.CharField(max_length=50)),
                ('historico_financiamentos', models.TextField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('termos_reembolso', models.TextField()),
                ('condicoes', models.TextField()),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('insumos', models.TextField()),
                ('ferramentas', models.TextField()),
                ('recursos_necessarios', models.TextField()),
                ('financiamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.financiamento')),
            ],
        ),
        migrations.CreateModel(
            name='Amortizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('historico_reembolsos', models.TextField()),
                ('financiamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.financiamento')),
            ],
        ),
    ]
